### ISSUE TITLE
GetAll使用报错

### ISSUE THREAD

**Issue by sedationh** [M010K/BauduWenkuSpider#1]
`Add MainContent Cost: 7.487329006195068s
-------------Start Convert--------------
Traceback (most recent call last):
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/configuration.py", line 21, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/GetAll.py", line 666, in <module>
    "").Run()
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/GetAll.py", line 627, in Run
    self.convertHtmlToPdf()
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/GetAll.py", line 598, in convertHtmlToPdf
    pdfkit.from_file(os.path.join(self.htmlsdirpath, str(self.startpage) + self.htmlfile), savepath, options=options)
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/api.py", line 47, in from_file
    configuration=configuration, cover_first=cover_first)
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/pdfkit.py", line 42, in __init__
    self.configuration = (Configuration() if configuration is None
  File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/configuration.py", line 27, in __init__
    'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf

Process finished with exit code 1`

**Comment by M010K** [comment]
wkhtmltopdf是不是没有安装？

**Comment by M010K** [comment]
> `Add MainContent Cost: 7.487329006195068s
> -------------Start Convert--------------
> Traceback (most recent call last):
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/configuration.py", line 21, in **init**
> with open(self.wkhtmltopdf) as f:
> FileNotFoundError: [Errno 2] No such file or directory: b''
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/GetAll.py", line 666, in
> "").Run()
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/GetAll.py", line 627, in Run
> self.convertHtmlToPdf()
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/GetAll.py", line 598, in convertHtmlToPdf
> pdfkit.from_file(os.path.join(self.htmlsdirpath, str(self.startpage) + self.htmlfile), savepath, options=options)
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/api.py", line 47, in from_file
> configuration=configuration, cover_first=cover_first)
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/pdfkit.py", line 42, in **init**
> self.configuration = (Configuration() if configuration is None
> File "/Users/sedationh/PycharmProjects/hard_python/baiduwenku/venv/lib/python3.7/site-packages/pdfkit/configuration.py", line 27, in **init**
> 'https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf' % self.wkhtmltopdf)
> OSError: No wkhtmltopdf executable found: "b''"
> If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
> 
> Process finished with exit code 1`

wkhtmltopdf是不是没有安装？

**Comment by sedationh** [comment]
🙈thank u
