### ISSUE TITLE
编码方式有问题

### ISSUE THREAD

**Issue by tunshu1987** [M010K/BauduWenkuSpider#4]
1、Getall第65行，建议增加utf-8编码方式，否则报错gbk无法解析某些字符。
2、判断是否为ppt类型的时候，有的时候有问题

**Comment by tunshu1987** [comment]
第2条是转换为pdf时，在获取font时为空，因此r.get(n)会报错。

**Comment by M010K** [comment]
> 1、Getall第65行，建议增加utf-8编码方式，否则报错gbk无法解析某些字符。
> 2、判断是否为ppt类型的时候，有的时候有问题

您好，方便的话能否提供一下报错的对应网址

**Comment by tunshu1987** [comment]
你好，第一个编码方式的问题，建议在红线处增加utf-8的编码方式，否则写入html的时候，中文有问题。
第二个是很多font为空，所以在获取内容的时候会报错，所以我直接注释掉了，见第二个图。
















在 2020-04-25 09:02:36，"M010K" <notifications@github.com> 写道：

1、Getall第65行，建议增加utf-8编码方式，否则报错gbk无法解析某些字符。
2、判断是否为ppt类型的时候，有的时候有问题

您好，方便的话能否提供一下报错的对应网址

**Comment by M010K** [comment]
> 你好，第一个编码方式的问题，建议在红线处增加utf-8的编码方式，否则写入html的时候，中文有问题。 第二个是很多font为空，所以在获取内容的时候会报错，所以我直接注释掉了，见第二个图。 在 2020-04-25 09:02:36，"M010K" <notifications@github.com> 写道： 1、Getall第65行，建议增加utf-8编码方式，否则报错gbk无法解析某些字符。 2、判断是否为ppt类型的时候，有的时候有问题 您好，方便的话能否提供一下报错的对应网址 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

utf-8 已经修改了，另外图片貌似加载不出来...
